### ISSUE TITLE
Gremlin: Zero Width Joiner U+200D

### ISSUE THREAD

**Issue by jabney** [nhoizey/vscode-gremlins#13] opened 2018-03-22 16:37 UTC
This one cost me time and sanity.

```javascript
{
 '200d':  {
    zeroWidth: true,
    description: 'zero width joiner',    
  }
}
```
https://unicode-table.com/en/200D/

**Comment by nhoizey** [comment] 2019-04-15 11:48
Closing this one as a duplicate of #16

**Closed by nhoizey** 2019-04-15 11:48 UTC
