### ISSUE TITLE
[Feature request] Autofix gremlins

### ISSUE THREAD

**Issue by PrzemyslawKlys** [nhoizey/vscode-gremlins#202] opened 2021-09-01 20:14 UTC
**Is your feature request related to a problem? Please describe.**
Ever since I encountered copy/paste issue from Microsoft Teams and wasted 2 days tracking 7 zero-width character in every single line of code from Teams I've started using your Gremlin tracker on a daily basis. This is where I noticed I actually have lots of those issues. Some critical, some not so much.

![image](https://user-images.githubusercontent.com/15063294/131737736-07bfb32b-5835-44f5-9bc5-a33f25b1fecc.png)

Since you already know what most of gremlins require (auto-deletion, replacements and so on) it would be great to have ability of auto-fixing known-issues.

**Describe the solution you'd like**
PowerShell extension for some problems allows you to click on the problem and have it fix it automatically. Of course fixing it for all found issues in file is also an option

![image](https://user-images.githubusercontent.com/15063294/131738447-9a5c9161-f561-49cf-974e-cb9a355f8e72.png)

**Describe alternatives you've considered**
Copy/Paste :-) Manual fixes which is what I do now

**Comment by TheSench** [comment] 2021-09-02 00:26
Duplicate of #23

**Closed by TheSench** 2021-09-02 00:26 UTC
